#!/bin/bash

function clears {
	clear
echo "$magenta"
echo ""
echo "
░█████╗░░█████╗░███╗░░██╗██████╗░██╗░░░██╗
██╔══██╗██╔══██╗████╗░██║██╔══██╗╚██╗░██╔╝
██║░░╚═╝███████║██╔██╗██║██║░░██║░╚████╔╝░
██║░░██╗██╔══██║██║╚████║██║░░██║░░╚██╔╝░░
╚█████╔╝██║░░██║██║░╚███║██████╔╝░░░██║░░░
░╚════╝░╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░░░░╚═╝░░░
"
echo ":: musicBotController"
echo ":: Author: Maciek \"Lukieer\" Skarbek"
echo ":: Version: 1.2.0"
echo ""
echo "$reset"
}


cd "$(dirname "$0")"

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
y=`tput setaf 3`
magenta=`tput setaf 5`
dist=`grep DISTRIB_ID /etc/*-release | awk -F '=' '{print $2}'`

clears

if [ "$1" == "install" ];
    then


		echo "Proszę wprowadzić system, z jakiego korzystasz (Debian | Ubuntu | Other) (WIELKOŚĆ LITER MA ZNACZENIE!) :"
		read system_name

		if [ "$system_name" == "Debian" ];
			then
				clears
				echo ":: Rozpoczynam instalacje dla systemu: Debian"
				echo ":: Aktualizowanie repozytoriów"
				apt-get update -y >/dev/null
				clears
				echo ":: Instalacja podstawowych narzędzi"
				apt-get install sudo screen htop wget curl -y >/dev/null
                sudo apt-get install sendmail -y >/dev/null
				clears
				echo ":: Trwa instalacja, proszę czekać"
				apt-get update -y >/dev/null
				apt-get upgrade -y >/dev/null
				sudo apt install -y lsb-release ca-certificates apt-transport-https software-properties-common >/dev/null
				echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/sury-php.list >/dev/null
				wget -qO – https://packages.sury.org/php/apt.gpg | sudo apt-key add – >/dev/null
				sudo apt update
				apt-get install php8.0 php8.0-gd php8.0-curl php8.0-cli php8.0-common php8.0-opcache php8.0-curl php8.0-mbstring php8.0-mysql php8.0-zip php8.0-xml -y
				clears
				echo ":: Trwa instalacja, proszę czekać"
				sudo apt update -y >/dev/null
				sudo apt install apache2 -y >/dev/null
				sudo apt install mariadb-server mariadb-client -y >/dev/null
				apt install php7.4 php7.4-cli php7.4-common php7.4-curl php7.4-gd php7.4-intl php7.4-json php7.4-mbstring php7.4-mysql php7.4-opcache php7.4-readline php7.4-xml php7.4-xsl php7.4-zip php7.4-bz2 libapache2-mod-php7.4 -y >/dev/null
				a2dismod php8.0 >/dev/null
				clears
				echo ":: Trwa instalacja, proszę czekać"
				sudo apt-get install phpmyadmin -y >/dev/null
                sudo apt-get install php-pear -y >/dev/null
                sudo apt install php-dev -y >/dev/null
				clears
				echo ":: Kończenie instalacji..."
				a2enmod rewrite >/dev/null
				sudo apt-get install php libapache2-mod-php
				sudo a2enmod mpm_prefork && sudo a2enmod php7.4
				service apache2 restart >/dev/null
				clears
				echo ":: Pomyślnie zainstalowano!"
				sleep 1
				clears
				echo ":: Instalacja zakończona powodzeniem!"

		elif [ "$system_name" == "Ubuntu" ];
			then
				clear
				clears
				echo ":: Rozpoczynam instalacje dla systemu: Debian"
				echo ":: Aktualizowanie repozytoriów"
				apt-get update -y >/dev/null
                sudo apt-get install sendmail -y >/dev/null
				clears
				echo ":: Instalacja podstawowych narzędzi"
				apt-get install sudo screen htop wget curl -y >/dev/null
				clears
				echo ":: Trwa instalacja, proszę czekać"
				apt-get update -y >/dev/null
				apt-get upgrade -y >/dev/null
				clears
				echo ":: Trwa instalacja, proszę czekać"
				sudo apt install software-properties-common -y >/dev/null
				sudo add-apt-repository ppa:ondrej/php -y >/dev/null
				sudo apt update -y >/dev/null
				apt-get install php8.0 php8.0-gd php8.0-curl php8.0-cli php8.0-common php8.0-opcache php8.0-curl php8.0-mbstring php8.0-mysql php8.0-zip php8.0-xml -y
				apt install php7.4 php7.4-cli php7.4-common php7.4-curl php7.4-gd php7.4-intl php7.4-json php7.4-mbstring php7.4-mysql php7.4-opcache php7.4-readline php7.4-xml php7.4-xsl php7.4-zip php7.4-bz2 libapache2-mod-php7.4 -y >/dev/null
				clears
				echo ":: Trwa instalacja, proszę czekać"
                sudo apt-get install php-pear -y >/dev/null
                sudo apt install php-dev -y >/dev/null
				a2dismod php8.0 >/dev/null
				sudo apt-get install phpmyadmin -y >/dev/null
				clears
				echo ":: Kończenie instalacji..."
				sudo apt-get install php libapache2-mod-php -y >/dev/null
				sudo a2enmod mpm_prefork && sudo a2enmod php7.4 >/dev/null
				a2enmod rewrite >/dev/null
				service apache2 restart >/dev/null
				clears
				echo ":: Pomyślnie zainstalowano!"
				sleep 1
				clears
		else 
			clears
			echo "Wybrany system nie jest obsługiwany przez naszego instalatora. Skontakuj się z autorem lub spróbuj na własną ręke zainstalować pakiet PHP 8.0, PHP 7.4, apache2 oraz MariaDB"
		fi
		echo ""


elif [ "$1" == "start" ];
	then
	sleep 1
		for (( i=1; $i <= 1; i++ )) ; do
			if screen -ls | grep -q Candy_MusicBot;
				then
					echo " :: $green POPRAWNIE $reset Instance $i Jest włączona $reset"
			else
				screen -AdmS Candy_MusicBot php app.php
				echo " :: $green POPRAWNIE $reset Instance $i $green Startowanie $reset"
			fi
		done
elif [ "$1" == "stop" ];
	then
		for (( i=1; $i <= 1; i++ )) ; do
			if screen -ls | grep -q Candy_MusicBot;
				then
					screen -X -S Candy_MusicBot quit
					echo " :: $green POPRAWNIE $reset Instance $i $red Zatrzymana...$reset"
			else
				echo " :: $red BŁĄD $reset Instance $i Instancja jest wyłączona $reset"
			fi
		done
elif [ "$1" == "restart" ];
	then
		
		for (( i=1; $i <= 1; i++ )) ; do
			if screen -ls | grep -q Candy_MusicBot;
			then
				screen -X -S Candy_MusicBot quit
				echo " :: $green POPRAWNIE $reset Instance $i Zatrzymana"
				screen -AdmS Candy_MusicBot php app.php
				echo " :: $green POPRAWNIE $reset Instance $i $green Startuje...$reset"
			else
				screen -AdmS Candy_MusicBot php app.php
				echo " :: $green POPRAWNIE $reset Instance $i $green Startuje...$reset"
			fi
		done
else
	echo "Correct usage: ./run <start|stop|restart|install>"
fi
